### ISSUE TITLE
minimal requirements?

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [conda-forge/extract_model-feedstock#19]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I notice that the requirements include:

    - cf_xarray
    - cmocean
    - dask <=2022.05.0
    - matplotlib-base
    - netcdf4
    - numba
    - numpy
    - python >=3.7
    - pytest
    - requests
    - scikit-learn
    - xarray
    - xcmocean
    - xoak
    
Most of these are indeed hard requirements, but some I assume are only required if you want to do visualization, etc, e.g. Cartopy, matplotlib, etc.

I think with conda packages, it's best to have as requirements only those packages that are required for core functionality.

Anyone that's using cartopy will know they need to install it anyway :-)

The challenge with being comprehensive is that folks then need to install a lot of unneeded stuff on production systems.

oh, and pytest shouldn't be included either.

### Installed packages

```shell
not relevant
```

### Environment info

```shell
not relevant
```

**Comment by kthyng** [comment]
This is being addressed in the new version: https://github.com/conda-forge/extract_model-feedstock/pull/20
